<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>ZBico.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Fonts\ParsiAripa.ttf" />
    <None Remove="Assets\Fonts\Vazirmatn-Medium.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ZBico.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\ParsiAripa.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Fonts\Vazirmatn-Medium.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="GregsStack.InputSimulatorStandard" Version="1.3.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MouseKeyHook" Version="5.7.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Assets\Resource\LanguageResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LanguageResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Assets\Resource\LanguageResources.peap.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LanguageResources.peap.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Assets\Resource\LanguageResources.peap.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>LanguageResources.peap.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Assets\Resource\LanguageResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>LanguageResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Database\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Database\ZibaNeveshChakameDataBase.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
