//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZibaNevesht.Assets.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZibaNevesht.Assets.Resource.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درود بر همگان، من خشایار هستم سازنده آترا آریپا پارس استودیو، مایه سربلندی است که شما برنامه من را بارگزاری کرده اید، نرم افزار ما آزاد و بیشتر برای سرگرمی آغاز شد اگرچه که  اکنون به یک نرم افزار گیرا و پر از سرگرمی دگرگون شده است، که میتوانید در آن با  جهانی  از واژگان فرو روید. همیشه در کوشیدن آن هستم که هر چه میسازم را بهبود سازم و از نادرستی یا لغزش های نرم افزار خود آموزه پیشه کنم و آنرا درست سازم، اگر کژی و لغزشی در این نرم افزار برایتان آشکار شد، بسیار خوشنود میشوم آنرا با من در یک Issue گیت هاب برای [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گیت‌هاب.
        /// </summary>
        public static string AboutGithub {
            get {
                return ResourceManager.GetString("AboutGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به .
        /// </summary>
        public static string AboutHeaderPrefix {
            get {
                return ResourceManager.GetString("AboutHeaderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  خوش آمدید.
        /// </summary>
        public static string AboutHeaderSuffix {
            get {
                return ResourceManager.GetString("AboutHeaderSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره من.
        /// </summary>
        public static string AboutHeaderTitle {
            get {
                return ResourceManager.GetString("AboutHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پل های پیوندگر.
        /// </summary>
        public static string AboutLinksTitle {
            get {
                return ResourceManager.GetString("AboutLinksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کانال شخصی من در تلگرام.
        /// </summary>
        public static string AboutPersonalTelegram {
            get {
                return ResourceManager.GetString("AboutPersonalTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کانال تلگرام.
        /// </summary>
        public static string AboutTelegramChannel {
            get {
                return ResourceManager.GetString("AboutTelegramChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وبگاه آریپا پارس — aripapars.top.
        /// </summary>
        public static string AboutWebsiteLink {
            get {
                return ResourceManager.GetString("AboutWebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string GoshBeZangAddButton {
            get {
                return ResourceManager.GetString("GoshBeZangAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودنِ بایسته.
        /// </summary>
        public static string GoshBeZangAddRequirement {
            get {
                return ResourceManager.GetString("GoshBeZangAddRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زدودن همگان.
        /// </summary>
        public static string GoshBeZangDeleteAll {
            get {
                return ResourceManager.GetString("GoshBeZangDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زدودنِ برگزیده.
        /// </summary>
        public static string GoshBeZangDeleteSelected {
            get {
                return ResourceManager.GetString("GoshBeZangDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رده سختی :.
        /// </summary>
        public static string GoshBeZangHardnessLevelFormat {
            get {
                return ResourceManager.GetString("GoshBeZangHardnessLevelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به .
        /// </summary>
        public static string GoshBeZangHeaderPrefix {
            get {
                return ResourceManager.GetString("GoshBeZangHeaderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش آمدید .
        /// </summary>
        public static string GoshBeZangHeaderSuffix {
            get {
                return ResourceManager.GetString("GoshBeZangHeaderSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گوش به زنگ.
        /// </summary>
        public static string GoshBeZangHeaderTitle {
            get {
                return ResourceManager.GetString("GoshBeZangHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام واژه:.
        /// </summary>
        public static string GoshBeZangItemNameFormat {
            get {
                return ResourceManager.GetString("GoshBeZangItemNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرستِ بایسته‌ها.
        /// </summary>
        public static string GoshBeZangListTitle {
            get {
                return ResourceManager.GetString("GoshBeZangListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برگزیدن رده ها .
        /// </summary>
        public static string GoshBeZangSelectCategories {
            get {
                return ResourceManager.GetString("GoshBeZangSelectCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره من.
        /// </summary>
        public static string MainTabAbout {
            get {
                return ResourceManager.GetString("MainTabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گوش به زنگ.
        /// </summary>
        public static string MainTabGoshBeZang {
            get {
                return ResourceManager.GetString("MainTabGoshBeZang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میشماره.
        /// </summary>
        public static string MainTabMishmare {
            get {
                return ResourceManager.GetString("MainTabMishmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیبا نوشت (چکامه نویسان).
        /// </summary>
        public static string MainTabZibaNevesht {
            get {
                return ResourceManager.GetString("MainTabZibaNevesht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دگرگونی رنگ (تاریک/روشن).
        /// </summary>
        public static string MainThemeToggleLabel {
            get {
                return ResourceManager.GetString("MainThemeToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به زیبا نوشت خوش آمدید.
        /// </summary>
        public static string MainWelcomeMessage {
            get {
                return ResourceManager.GetString("MainWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در فهرست سوی راست بیشترین واژگان بهره‌مند شده را ببینید و با جستجوی واژه می‌توانید شمارگان بهره‌مندی آن پی ببرید..
        /// </summary>
        public static string MishmareDescription {
            get {
                return ResourceManager.GetString("MishmareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به .
        /// </summary>
        public static string MishmareHeaderPrefix {
            get {
                return ResourceManager.GetString("MishmareHeaderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  خوش آمدید.
        /// </summary>
        public static string MishmareHeaderSuffix {
            get {
                return ResourceManager.GetString("MishmareHeaderSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میشماره.
        /// </summary>
        public static string MishmareHeaderTitle {
            get {
                return ResourceManager.GetString("MishmareHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشترین واژگان.
        /// </summary>
        public static string MishmareMostUsedWordsTitle {
            get {
                return ResourceManager.GetString("MishmareMostUsedWordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زدودن همه.
        /// </summary>
        public static string MishmareRemoveAll {
            get {
                return ResourceManager.GetString("MishmareRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی واژه.
        /// </summary>
        public static string MishmareSearchWordLabel {
            get {
                return ResourceManager.GetString("MishmareSearchWordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string MishmareShowButton {
            get {
                return ResourceManager.GetString("MishmareShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بهرهمندی:.
        /// </summary>
        public static string MishmareUsageFormat {
            get {
                return ResourceManager.GetString("MishmareUsageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باباطاهر.
        /// </summary>
        public static string PoetBabaTaher {
            get {
                return ResourceManager.GetString("PoetBabaTaher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حافظ.
        /// </summary>
        public static string PoetHafez {
            get {
                return ResourceManager.GetString("PoetHafez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیام.
        /// </summary>
        public static string PoetKhayyam {
            get {
                return ResourceManager.GetString("PoetKhayyam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رودکی.
        /// </summary>
        public static string PoetRodaki {
            get {
                return ResourceManager.GetString("PoetRodaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعدی.
        /// </summary>
        public static string PoetSaadi {
            get {
                return ResourceManager.GetString("PoetSaadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از چکامه‌سرایان را برگزیده و دگمه را بروشنید.
        /// </summary>
        public static string ZibaNeveshtDescription {
            get {
                return ResourceManager.GetString("ZibaNeveshtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آغازیدن به کار.
        /// </summary>
        public static string ZibaNeveshtStartButton {
            get {
                return ResourceManager.GetString("ZibaNeveshtStartButton", resourceCulture);
            }
        }
    }
}
