//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZibaNevesht.Assets.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources_peap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources_peap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZibaNevesht.Assets.Resource.LanguageResources.peap", typeof(LanguageResources_peap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دذرضد بار هامعگآن، مان خاشآیآر هاستام، سآزاندعق آترآ آرثپآ پآرس عستصدثذ، مآیع ساربذلاندث است کع شذمآ بارنآمعق مان رآ بآرگذزآرث کاردثد، نارم عفزآر مآ آزآد و بثشتر بارآی سارگرمث آغآز شدد اگرچع کع اکندون بع ثک نارم عفزآر گثرآ و پر از سارگرمث دگرگدون شددع است، کع مثةتوانثد در آن بآ جهآنث از واژگآن فرذ رئثد. همثشع در کئشثدن آن هاستام کع هر چع مثةسآزام رآ بهبئد سآزام و از نادرستث یآ لغزش هآی نارم عفزآر خئد آمئزع پثشع کنم و آنرآ درست سآزام، اگر کژث و لغزشث در اثن نارم عفزآر بارآیتآن آشکارآ شدد، بسخار خئشنئد مثةشئم [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گثت هآب.
        /// </summary>
        public static string AboutGithub {
            get {
                return ResourceManager.GetString("AboutGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بع.
        /// </summary>
        public static string AboutHeaderPrefix {
            get {
                return ResourceManager.GetString("AboutHeaderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  خذش آماوث.
        /// </summary>
        public static string AboutHeaderSuffix {
            get {
                return ResourceManager.GetString("AboutHeaderSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داربارع مط.
        /// </summary>
        public static string AboutHeaderTitle {
            get {
                return ResourceManager.GetString("AboutHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذل حآی پعیوطدگار.
        /// </summary>
        public static string AboutLinksTitle {
            get {
                return ResourceManager.GetString("AboutLinksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کآنآل شaxسی مط دار فعلگرآم.
        /// </summary>
        public static string AboutPersonalTelegram {
            get {
                return ResourceManager.GetString("AboutPersonalTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کآنآل فعلگرآم.
        /// </summary>
        public static string AboutTelegramChannel {
            get {
                return ResourceManager.GetString("AboutTelegramChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وعبگآح آریپآ پآرس — aripapars.top.
        /// </summary>
        public static string AboutWebsiteLink {
            get {
                return ResourceManager.GetString("AboutWebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزضدط.
        /// </summary>
        public static string GoshBeZangAddButton {
            get {
                return ResourceManager.GetString("GoshBeZangAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزضدانط بآیعستع.
        /// </summary>
        public static string GoshBeZangAddRequirement {
            get {
                return ResourceManager.GetString("GoshBeZangAddRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زذدضدان حامعگط.
        /// </summary>
        public static string GoshBeZangDeleteAll {
            get {
                return ResourceManager.GetString("GoshBeZangDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زذدذدطع بارگذزثدع.
        /// </summary>
        public static string GoshBeZangDeleteSelected {
            get {
                return ResourceManager.GetString("GoshBeZangDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رادع ساخفث : .
        /// </summary>
        public static string GoshBeZangHardnessLevelFormat {
            get {
                return ResourceManager.GetString("GoshBeZangHardnessLevelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بع .
        /// </summary>
        public static string GoshBeZangHeaderPrefix {
            get {
                return ResourceManager.GetString("GoshBeZangHeaderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خذش آماوث .
        /// </summary>
        public static string GoshBeZangHeaderSuffix {
            get {
                return ResourceManager.GetString("GoshBeZangHeaderSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذش بع زطگ.
        /// </summary>
        public static string GoshBeZangHeaderTitle {
            get {
                return ResourceManager.GetString("GoshBeZangHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام واژع : .
        /// </summary>
        public static string GoshBeZangItemNameFormat {
            get {
                return ResourceManager.GetString("GoshBeZangItemNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعحرسفعع بآیسفعحآ.
        /// </summary>
        public static string GoshBeZangListTitle {
            get {
                return ResourceManager.GetString("GoshBeZangListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگعزثدط رادع حآ .
        /// </summary>
        public static string GoshBeZangSelectCategories {
            get {
                return ResourceManager.GetString("GoshBeZangSelectCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داربارع مط.
        /// </summary>
        public static string MainTabAbout {
            get {
                return ResourceManager.GetString("MainTabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذش بع زطگ.
        /// </summary>
        public static string MainTabGoshBeZang {
            get {
                return ResourceManager.GetString("MainTabGoshBeZang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثشمآرع.
        /// </summary>
        public static string MainTabMishmare {
            get {
                return ResourceManager.GetString("MainTabMishmare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زثبآ نعوعشف (چکآمع نعوثسظ).
        /// </summary>
        public static string MainTabZibaNevesht {
            get {
                return ResourceManager.GetString("MainTabZibaNevesht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دعگارگذنث رطگ (فآرثک/رذشط).
        /// </summary>
        public static string MainThemeToggleLabel {
            get {
                return ResourceManager.GetString("MainThemeToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بع زثبآ نعوعشف خذش آماوث.
        /// </summary>
        public static string MainWelcomeMessage {
            get {
                return ResourceManager.GetString("MainWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دار فعحرسفع سذی راسف بثشفارق واژعگط باحرعماند شذدع رآ عبثنثد وا بآ یذسفذیذی واژع مثفآوآنثد شذمآرگط باحرعماندث ط پث عبعبرثد..
        /// </summary>
        public static string MishmareDescription {
            get {
                return ResourceManager.GetString("MishmareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بع .
        /// </summary>
        public static string MishmareHeaderPrefix {
            get {
                return ResourceManager.GetString("MishmareHeaderPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  خذش آماوث.
        /// </summary>
        public static string MishmareHeaderSuffix {
            get {
                return ResourceManager.GetString("MishmareHeaderSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثشمآرع.
        /// </summary>
        public static string MishmareHeaderTitle {
            get {
                return ResourceManager.GetString("MishmareHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بثشفارق واژعگط.
        /// </summary>
        public static string MishmareMostUsedWordsTitle {
            get {
                return ResourceManager.GetString("MishmareMostUsedWordsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زذدضدانط هامع.
        /// </summary>
        public static string MishmareRemoveAll {
            get {
                return ResourceManager.GetString("MishmareRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یذسفذیذع واژع.
        /// </summary>
        public static string MishmareSearchWordLabel {
            get {
                return ResourceManager.GetString("MishmareSearchWordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامآیعش.
        /// </summary>
        public static string MishmareShowButton {
            get {
                return ResourceManager.GetString("MishmareShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باحرعماندث:.
        /// </summary>
        public static string MishmareUsageFormat {
            get {
                return ResourceManager.GetString("MishmareUsageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بآبآفآحعر.
        /// </summary>
        public static string PoetBabaTaher {
            get {
                return ResourceManager.GetString("PoetBabaTaher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حآفعز.
        /// </summary>
        public static string PoetHafez {
            get {
                return ResourceManager.GetString("PoetHafez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاییآم.
        /// </summary>
        public static string PoetKhayyam {
            get {
                return ResourceManager.GetString("PoetKhayyam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رضدع کث.
        /// </summary>
        public static string PoetRodaki {
            get {
                return ResourceManager.GetString("PoetRodaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعذث.
        /// </summary>
        public static string PoetSaadi {
            get {
                return ResourceManager.GetString("PoetSaadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یعکث از چکآمعسارآیظ رآ بارگذزثدع وا دذگمع رآ بعرذشانثد.
        /// </summary>
        public static string ZibaNeveshtDescription {
            get {
                return ResourceManager.GetString("ZibaNeveshtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آغآزثدط بع کآر.
        /// </summary>
        public static string ZibaNeveshtStartButton {
            get {
                return ResourceManager.GetString("ZibaNeveshtStartButton", resourceCulture);
            }
        }
    }
}
