// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZibaNevesht.Services;

#nullable disable

namespace ZibaNevesht.Migrations
{
    [DbContext(typeof(DBmanager))]
    [Migration("20260823221828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.18");

            modelBuilder.Entity("ZibaNevesht.Services.ZBchamekade", b =>
                {
                    b.Property<int>("ChameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChameText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChameID");

                    b.ToTable("ZBchamekade");
                });

            modelBuilder.Entity("ZibaNevesht.Services.ZBgoshBeZang", b =>
                {
                    b.Property<string>("NameWord")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlertLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("NameWord");

                    b.ToTable("ZBgoshBeZang");
                });

            modelBuilder.Entity("ZibaNevesht.Services.ZBmishmare", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfUsedWord")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("ZBmishmare");
                });
#pragma warning restore 612, 618
        }
    }
}
